import { useState } from 'react';
import Button from '../components/common/Button';
import { useNavigate } from 'react-router-dom';
import Input from '../components/common/Input';

/**
 * Join Room Room Component
 * @returns JSX
 */
const JoinRoom: React.FC = () => {
  const [roomID, setRoomID] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleNavigation = () => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      navigate(`/game/${roomID}`);
    }, 2000);
  };

  return (
    <div className="w-[90%] max-w-[500px] filter backdrop-blur-2xl mx-auto justify-center items-center flex flex-col rounded-lg font-poppins text-center p-10">
      <h2 className="text-4xl font-bold text-white">
        Ready to win, Bond and Have Fun?
      </h2>

      <p className="my-4 text-white">
        Enter the Code generated by your friend to begin.
      </p>

      <Input
        value={roomID}
        placeholder="Enter 7-digit Room Code"
        otherProps={{ autoComplete: 'off' }}
        onChange={(text) => setRoomID(text)}
      />

      {/* Submit User Entry */}
      <Button
        disabled={loading}
        loading={loading}
        color="green"
        size="full"
        text={loading ? 'Loading. Please wait...' : 'Join Game'}
        onClick={handleNavigation}
      />
    </div>
  );
};

export default JoinRoom;
