name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight (adjust as needed)
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set Up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/RyanTk03/CMORSS-Tic-Tac-Toe.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push Changes to Forked Repository
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Backend Deployment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/mikiyas-girma/cmorss/dispatches \
            -d '{"event_type":"deploy_backend"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Frontend Deployment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/mikiyas-girma/cmorss/dispatches \
            -d '{"event_type":"deploy_frontend"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
